GastoTransparenteMunicipal/GastoTransparenteMunicipal/Controllers/AdminComunaController.cs
using System;
using System.Collections.Generic;
using GastoTransparenteMunicipal.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core;
using Newtonsoft.Json;
using System.Threading.Tasks;
using NPOI.XSSF.UserModel;
using System.IO;
using GastoTransparenteMunicipal.Helpers;
using System.Data.SqlClient;
using NPOI.SS.UserModel;
using System.Data.Entity;
using System.Data;
using System.Text;
using Microsoft.WindowsAzure.Storage.Blob;
using AutoMapper;

namespace GastoTransparenteMunicipal.Controllers
{
    [AuthorizeComuna]
    public class AdminComunaController : BaseController
    {
        private const string errorPassword = "Error Password";
        private const string errorMessage = "Error al leer el tipo de dato en columna numero {0}, el valor es diferente del esperado.";
        private const string errorCarga = "Error de carga";
        private const string okMessage = "OK";

        private string ErrorLoadExcel(Exception ex)
        {
            var position = ((AutoMapper.AutoMapperMappingException)ex).PropertyMap.CustomExpression.ToString().IndexOf("GetCell");
            position = position + 8;
            var columnPositionString = ((AutoMapper.AutoMapperMappingException)ex).PropertyMap.CustomExpression.ToString().Substring(position, 1);
            var columnPositionint = 0;
            int.TryParse(columnPositionString, out columnPositionint);
            columnPositionint++;
            var message = string.Format(errorMessage, columnPositionint);
            return message;
        }

        public StringBuilder StringCSV<T>(List<T> listItem)
        {
            ConvertTo convert = new ConvertTo();            
            var dt = convert.DataTable(listItem);

            StringBuilder sb = new StringBuilder();
            IEnumerable<string> columnNames = dt.Columns.Cast<DataColumn>().Select(column => column.ColumnName);

            sb.AppendLine(string.Join("|", columnNames));

            foreach (DataRow row in dt.Rows)
            {
                IEnumerable<string> fields = row.ItemArray.Select(field => field.ToString().Replace(System.Environment.NewLine, " "));

                string line = string.Join("|", fields);
                string result = System.Text.RegularExpressions.Regex.Replace(line, @"\r\n?|\n", " ");
                sb.AppendLine(result);
            }            

            return sb;
        }

        public string UploadCSV(string fileName, StringBuilder data)
        {
            BlobService blobService = new BlobService(GetAccountName, GetAccountKey);
            var blob = blobService.UploadBlob(fileName, "dataset", data);
            return blob.Uri.AbsoluteUri;
        }
        
        public ActionResult Index()
        {
            var municipalidad = GetCurrentIdMunicipality();
            ViewBag.logo = municipalidad.DireccionWeb + ".png";
            ViewBag.administracion = true;
            ViewBag.admimuni = true;
            ViewBag.anoscargados = municipalidad.Gasto_Ano.ToList() ;
            ViewBag.activos = new bool[4]{
                municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
            };
            return View();
        }

        public ActionResult CargaDatos()
        {
            var municipalidad = GetCurrentIdMunicipality();            
            ViewBag.logo = municipalidad.DireccionWeb + ".png";
            ViewBag.Destacado = "hidden";
            ViewBag.administracion = true;
            ViewBag.admimuni = true;
            List<Anos_Invisible> lista = db.Anos_Invisible.Where(r => r.IdMunicipalidad == municipalidad.IdMunicipalidad).ToList();
            ViewBag.contador = lista.Count;
            ViewBag.Anos = new SelectList(lista, "IdAno", "Nombre");
            ViewBag.activos = new bool[4]{
                municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
            };
            return View();
        }

        [HttpPost]
        public ActionResult CargaDatos(int id)
        {
            IncreaseTimeOutDb();

            Gasto_Ano gasto = db.Gasto_Ano.Find(id);

            var gastos = db.Gasto_Ano.Where(            r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();
            var ingresos = db.Ingreso_Ano.Where(        r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();
            var proveedors = db.Proveedor_Ano.Where(    r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();
            var subsidios = db.Subsidio_Ano.Where(      r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();
            var corporacions = db.Corporacion_Ano.Where(r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();
            var personals = db.Personal_Ano.Where(      r => r.Ano == gasto.Ano &&  r.IdMunicipalidad == gasto.IdMunicipalidad).ToList();

            if (gastos.Count > 0)
            {
                for (int i = 0; i < gastos.Count; i++)
                {
                    if(gastos[i].Semestre== gasto.Semestre)
                    {
                        gastos[i].Activo = true;
                    }
                    else
                    {
                        gastos[i].Activo = false;
                        db.SP_DeleteGasto(gastos[i].IdAno);
                    }
                }
            }
            if (ingresos.Count > 0)
            {
                for (int i = 0; i < ingresos.Count; i++)
                {
                    if (ingresos[i].Semestre == gasto.Semestre)
                    {
                        ingresos[i].Activo = true;
                    }
                    else
                    {
                        ingresos[i].Activo = false;
                        db.SP_DeleteIngreso(ingresos[i].IdAno);
                    }
                    
                }
            }
            if (proveedors.Count > 0)
            {
                for (int i = 0; i < proveedors.Count; i++)
                {
                    if (proveedors[i].Semestre == gasto.Semestre)
                    {
                        proveedors[i].Activo = true;
                    }
                    else
                    {
                        proveedors[i].Activo = false;
                        db.SP_DeleteProveedor(proveedors[i].IdAno);
                    }

                }
            }
            if (subsidios.Count > 0)
            {
                for (int i = 0; i < subsidios.Count; i++)
                {
                    if (subsidios[i].Semestre == gasto.Semestre)
                    {
                        subsidios[i].Activo = true;
                    }
                    else
                    {
                        subsidios[i].Activo = false;
                        db.SP_DeleteSubsidio(subsidios[i].IdAno);
                    }

                }
            }
            if (corporacions.Count > 0)
            {
                for (int i = 0; i < corporacions.Count; i++)
                {
                    if (corporacions[i].Semestre == gasto.Semestre)
                    {
                        corporacions[i].Activo = true;
                    }
                    else
                    {
                        corporacions[i].Activo = false;
                        db.SP_DeleteCorporacion(corporacions[i].IdAno);
                    }

                }
            }
            if (personals.Count > 0)
            {
                for (int i = 0; i < personals.Count; i++)
                {
                    if (personals[i].Semestre == gasto.Semestre)
                    {
                        personals[i].Activo = true;
                    }
                    else
                    {
                        personals[i].Activo = false;
                        db.SP_DeletePersonal(personals[i].IdAno);
                    }

                }
            }
            db.SaveChanges();

            Gasto_Ano maxAno = db.Gasto_Ano.Where(r=>r.IdMunicipalidad==gasto.IdMunicipalidad && r.Activo==true).OrderByDescending(r=>r.Ano).First();            
            var suma = db.SP_SumaGastoByIdAno(maxAno.IdAno).First();
            Municipalidad municipalidad = db.Municipalidad.Find(maxAno.IdMunicipalidad);
            switch (maxAno.Semestre)
            {
                case 0:
                    municipalidad.Periodo = "El " + maxAno.Ano +" "; 
                    break;
                case 1:
                    municipalidad.Periodo = "A Marzo de " + maxAno.Ano + " ";
                    break;
                case 2:
                    municipalidad.Periodo = "A Junio de " + maxAno.Ano + " ";
                    break;
                case 3:
                    municipalidad.Periodo = "A Septiembre de " + maxAno.Ano + " ";
                    break;
            }
            municipalidad.TotalGastado = "$"+ Ppuntos(suma.TotalGastado.Value);
            municipalidad.TotalPresupuestado = "$" + Ppuntos(suma.TotalPresupuestado.Value);
            db.SaveChanges();

            return RedirectToAction ("CargaDatosOk");
        }

        public ActionResult CargaDatosOk()
        {
            var municipalidad = GetCurrentIdMunicipality();
            ViewBag.logo = municipalidad.DireccionWeb + ".png";
            ViewBag.Destacado = "hidden";
            ViewBag.administracion = true;
            return View();
        }



        string Ppuntos(long aux2 )
        {
            string aux = Convert.ToString(aux2);
            char[] charArray = aux.ToCharArray();
            Array.Reverse(charArray);
            aux = new string(charArray);


            string puntos = "";
            for (var i=0; i < aux.Length; i++)
            {
                if ((i+1) % 3 == 0 )
                {

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/AbrirPeriodo.cshtml
@{
    ViewBag.Title = "Abrir nuevo Periodo";
}

<div class="container">
    <div class="row seccion-destado">

        <div class="col-md-12">
            <h1>
                Abrir nuevo periodo
            </h1>
        </div>
        <div class="col-md-12">
            @using (Html.BeginForm("AbrirPeriodo", "AdminComuna", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="form-group">
                Año
                @Html.DropDownList("ano", (SelectList)ViewBag.ano, null, new { @class = "form-control", @id = "ano" })
            </div>
            <div class="form-group">
                Periodo
                @Html.DropDownList("periodo", (SelectList)ViewBag.periodo, null, new { @class = "form-control", @id = "periodo" })
            </div>
            <input type ="hidden" id="anoactual" value="@DateTime.Now.Year" />
            <input type ="hidden" id="idMuni" value="@ViewBag.idMuni" />
            <div class="form-group">
                <p class="text-right">
                    <input type="submit" class="btn btn-primary" value="Abrir Periodo" />
                </p>
            </div>
            }
        </div>
    </div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div"></div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#ano").change(function () {
                if ($("#ano").val() == $("#anoactual").val()) {
                    $.ajax({
                        cache: false,
                        async: false,
                        type: 'POST',
                        data: {
                            ano: parseInt($("#ano").val()),
                            idMuni: parseInt($("#idMuni").val())
                        },
                        url: '@Url.Action("FiltroMeses", "AdminComuna")',
                        dataType: 'json',
                        success: function (data) {
                            $("#periodo option[value='0']").remove();
                            $("#periodo option[value='1']").remove();
                            $("#periodo option[value='2']").remove();
                            $("#periodo option[value='3']").remove();
                            var aux = false;
                            $.each(data, function (i, item) {
                                if (item == 0) {
                                    aux = true;
                                } else if (item == 1) {
                                    $('#periodo').append('<option value="1" >a Marzo</option>');
                                } else if (item == 2) {
                                    $('#periodo').append('<option value="2" >a Junio</option>');
                                } else if (item == 3) {
                                    $('#periodo').append('<option value="3" >a Septiembre</option>');
                                }
                            });
                            if (aux == true) {
                                $('#periodo').append('<option value="0" >Completo</option>');
                            }
                        },
                        error: function (msg) {
                        }
                    });
                }
                else {
                    $("#periodo option[value='0']").remove();
                    $("#periodo option[value='1']").remove();
                    $("#periodo option[value='2']").remove();
                    $("#periodo option[value='3']").remove();
                    $('#periodo').append('<option value="0" >Completo</option>');
                }
                
                
            });
        });
    </script>

}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaCorporaciones.cshtml
@{
    ViewBag.Title = "Carga Corporaciones";
}


<div class="container">
    <div class="row seccion-destado">
        @if (ViewBag.aviso)
        {
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    Esta informacion ya se encuentra cargada, si la vuelve a cargar se reemplaza la anterior.
                </div>
            </div>
        }

        <div class="col-md-12">
            <h1>
                Carga de Corporaciones año
                <span class="muntotal">
                    @ViewBag.ano
                </span>
                <br />
                <br />
            </h1>
        </div>
        <div class="col-md-12">
            <form action="@Url.Action("CargaCorporaciones","AdminComuna")" id="formulario" method="post" enctype="multipart/form-data">
                <input type="hidden" id="id" value="@ViewBag.id" />
                <h4 class="inline">
                    <img src="~/Content/image/mal.png" id="error" style="display:none" alt="archivo correcto" />
                    <img src="~/Content/image/bien.png" id="success" style="display:none" alt="archivo con errores" />
                    Municipio Total &nbsp;&nbsp;&nbsp;
                </h4>
                <p class="inline">
                    <small>
                        <input type="file" accept=".xls,.xlsx" id="file" name="file" />
                        <input type="hidden" id="fileStatus" />        
                        <label id="messagefileStatus" />
                    </small>
                </p>
                <hr />
                <input type="submit" class="btn" id="boton" value="Confirmar subida de Información" disabled>
            </form>
        </div>
    </div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div"></div>
</div>

@section scripts{
    <script>
    $(document).ready(function () {

        $("#file").on("change", function () {
            upload('@Url.Action("ValidadorCargaCorporaciones", "AdminComuna")', 'file', 'fileStatus')
        });       

        //SI TODOS LOS HIDDEN

        $("#boton").on("click",function () {
            //si todos los type hidden en true, realiza el submit():
            if (1 == 1) {
                document.getElementById('formulario').submit();
            }
        });

        function upload(urlPath, name, result) {
            var isValid = undefined;
            var formData = new FormData();
            var file = document.getElementById(name).files[0];
            formData.append(name, file);
            $.ajax({
                type: 'post',
                url: urlPath,
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    $("#" + result).val(response.isValid);
                    $("#message" + result).text(response.message);
                    checkSingleStatus(name, response.isValid);
                    checkAllStatus();
                }
            });
        }

        function checkAllStatus() {
            var isValid = $('#fileStatus').val();
    
            if (isValid == "true") {
                $('#boton').prop("disabled", false);
            } else {
                $('#boton').prop("disabled", true);
            }
            
        }

        function checkSingleStatus(item, result) {
            if (item == "file") {
                if (result == true) {
                    $('#success').css("display", "inline");
                    $('#error').css("display", "none");
                }
                else {
                    $('#success').css("display", "none");
                    $('#error').css("display", "inline");
                }
            }         
        }
    });
    </script>
}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaDatos.cshtml
@{
    ViewBag.Title = "CargaDatos";
}

<div class="container">
    <div class="row seccion-destado">

        <div class="col-md-12">
            <h1>
                Carga de información año
                <small>
                    del año:
                    @if (ViewBag.contador != 0)
                    {
                    <span class="select" style="">
                        @Html.DropDownList("name", (SelectList)ViewBag.Anos, null, new { @class = "muntotal", @id = "Anos" })
                    </span>
                    }


                </small>
                <small style="font-size:30%">
                    <a class="btn btn-xs" href="@Url.Action("AbrirPeriodo","AdminComuna")">( +abrir nuevo año )</a>
                </small>
            </h1>
        </div>
        <div class="col-md-12">
            <h2>Ingresos <small id="ingreso" class="paneladmin"></small></h2>
            <h2>Gastos <small id="gasto" class="paneladmin"></small></h2>
            <input type="hidden" id="dat0" value="@ViewBag.activos[0]" />
            <input type="hidden" id="dat1" value="@ViewBag.activos[1]" />
            <input type="hidden" id="dat2" value="@ViewBag.activos[2]" />
            <input type="hidden" id="dat3" value="@ViewBag.activos[3]" />

            @if (ViewBag.activos[0])
            {
                <h2><span>Proveedores</span> <small id="proveedor" class="paneladmin"></small></h2>
            }
            @if (ViewBag.activos[1])
            {
                <h2><span>Subsidios</span> <small id="subsidio" class="paneladmin"></small></h2>
            }
            @if (ViewBag.activos[2])
            {
                <h2><span>Corporaciones</span> <small id="corporacion" class="paneladmin"></small></h2>
            }
            @if (ViewBag.activos[3])
            {
                <h2><span>Remuneraciones</span> <small id="remuneracion" class="paneladmin"></small></h2>
            }
            <form action="@Url.Action("CargaDatos","AdminComuna")" id="formulario" method="post" enctype="multipart/form-data">
                <h2 class="text-right">
                    <input type="hidden" name="id" id="anopost" />
                    <span class="cssToolTip"><span class="md-24 icon-Recurso-help amarillo"></span><span class="oculto" style="font-size:12px">Primero tienes que tener cargada la información. Para que se active el boton. Si tienes otro periodo cargado  de este año, se eliminara automaticamente.</span></span>
                    <button type="submit" class="btn btn-primary blanco" id="aceptarFinal" disabled="disabled">Activar Periodo</button>
                    <a href="@Url.Action("Eliminar","AdminComuna")" class="btn btn-transparente btn-xs"><small>Elimina periodos</small></a>
                </h2>
            </form>
        </div>
    </div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div">
    </div>
</div>

@section scripts{
    <script src="~/Scripts/select.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {

            $("select").resizeselect();
            $("#anopost").val($("#Anos").val());
            Verdisponibilidad();

            $("#Anos").change(function () {
                Verdisponibilidad();
                $("#anopost").val($("#Anos").val());
            });

        });

        function Verdisponibilidad() {
            
            if ($("#Anos").val() != null) {
                var suma = 2, contador = 0;
                var aaa = $("#dat0").val();
                if ($("#dat0").val() == "value") {
                    suma = suma + 1;
                }
                if ($("#dat1").val() == "value") {
                    suma = suma + 1;
                }
                if ($("#dat2").val() == "value") {
                    suma = suma + 1;
                }
                if ($("#dat3").val() == "value") {
                    suma = suma + 1;
                }
                $.ajax({
                    cache: false,
                    async: false,
                    type: 'POST',
                    data: {
                        aux: $("#Anos").val()
                    },
                    url: '../AdminComuna/CargadosPost',
                    dataType: 'json',
                    success: function (data) {
                        var URLactual = window.location.pathname;
                        var tabla = URLactual.split('/')
                        var ano = $("#Anos").val();
                        
                        if (!data[0]) {
                            $("#ingreso").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaIngresos/" + ano + "'> +Cargar información</a>");
                        } else {
                            contador = contador + 1;
                            $("#ingreso").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (!data[1]) {
                            $("#gasto").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaGastos/" + ano + "'> +Cargar información</a>");
                        } else {
                            contador = contador + 1;
                            $("#gasto").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (!data[2]) {
                            $("#proveedor").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaProveedores/" + ano + "'> +Cargar información</a>");
                        } else {
                            contador = contador + 1;
                            $("#proveedor").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (!data[3]) {
                            $("#subsidio").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaSubsidios/" + ano + "'> +Cargar información</a>");
                        } else {
                            contador = contador + 1;
                            $("#subsidio").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (!data[4]) {
                            $("#corporacion").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaCorporaciones/" + ano + "'> +Cargar información</a>");;
                        } else {
                            contador = contador + 1;
                            $("#corporacion").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (!data[5]) {
                            $("#remuneracion").html("<a href='../../../" + tabla[1] + '/' + tabla[2] + "/CargaRemuneraciones/" + ano + "'> +Cargar información</a>");
                        } else {
                            contador = contador + 1;
                            $("#remuneracion").html("<img src='../../../Content/image/bien.png' class='subimg' alt='Archivo ya cargado'/>");
                        }
                        if (contador == suma) {
                            $("#aceptarFinal").removeAttr("disabled")
                        }

                    },
                    error: function (msg) {
                        $('#btnagendar').attr('disabled', false);
                    }
                });
            }
        }
        
    </script>
}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaDatosOk.cshtml
@{
    ViewBag.Title = "Cargado Ok";
}

<div class="container">
    <div class="row seccion-destado">
        <div class="col-md-12">
            <h1>
                Carga realizada correctamente.
            </h1>
        </div>
        <div class="col-md-12">
            <p>
                <br /><br /><br /><br />
                <a href="@Url.Action("CargaDatos","AdminComuna")" class="btn btn-primary">Volver</a>
            </p>
        </div>
    </div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div">
    </div>
</div>

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaDiccionarioGastos.cshtml
@{
    ViewBag.Title = "CargaDiccionarioGastos";
}

<h2>CargaGlosaGastos</h2>

<div class="col-md-12">
    <form action="@Url.Action("CargaDiccionarioGastos","AdminComuna")" id="formulario" method="post" enctype="multipart/form-data">
        <label>
            <span></span>
            Adm. y Serv. Municipales
            <input type="file" accept=".xls,.xlsx" id="file" name="file" />
            <input type="hidden" />
        </label><br />
        <input type="submit" class="btn" id="boton" value="Confirmar subida de Informacion">
    </form>
</div>

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaDiccionarioIngresos.cshtml
@{
    ViewBag.Title = "CargaDiccionarioIngresos";
}

<h2>CargaGlosaGastos</h2>

<div class="col-md-12">
    <form action="@Url.Action("CargaDiccionarioIngresos","AdminComuna")" id="formulario" method="post" enctype="multipart/form-data">
        <label>
            <span></span>
            Adm. y Serv. Municipales
            <input type="file" accept=".xls,.xlsx" id="file" name="file" />
            <input type="hidden" />
        </label><br />
        <input type="submit" class="btn" id="boton" value="Confirmar subida de Informacion">
    </form>
</div>

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/AdminComuna/CargaSubsidios.cshtml
@{
    ViewBag.Title = "Carga Subsidios";
}


<div class="container">
    <div class="row seccion-destado">
        @if (ViewBag.aviso)
        {
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    Esta informacion ya se encuentra cargada, si la vuelve a cargar se reemplaza la anterior.
                </div>
            </div>
        }

        <div class="col-md-12">
            <h1>
                Carga de Subsidios año
                <span class="muntotal">
                    @ViewBag.ano
                </span>
                <br /><br />
            </h1>
        </div>
        <div class="col-md-12">
            <form action="@Url.Action("CargaSubsidios","AdminComuna")" id="formulario" method="post" enctype="multipart/form-data">
                <input type="hidden" id="id" value="@ViewBag.id" />
                <h4 class="inline">
                    <img src="~/Content/image/mal.png" id="error" style="display:none" alt="archivo correcto" />
                    <img src="~/Content/image/bien.png" id="success" style="display:none" alt="archivo con errores" />
                    Municipio Total &nbsp;&nbsp;&nbsp;
                </h4>
                <p class="inline">
                    <small>
                        <input type="file" accept=".xls,.xlsx" id="file" name="file" />
                        <input type="hidden" id="fileStatus" />
                        <label id="messagefileStatus" />
                    </small>
                </p>
                <hr />
                <input type="submit" class="btn" id="boton" value="Confirmar subida de Información" disabled>
            </form>
        </div>
    </div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div"></div>
    <div class="row padding-Div"></div>
</div>

@section scripts{
    <script>
    $(document).ready(function () {

        $("#file").on("change", function () {
            upload('@Url.Action("ValidadorCargaSubsidios", "AdminComuna")', 'file', 'fileStatus')
        });

        //SI TODOS LOS HIDDEN

        $("#boton").on("click",function () {
            //si todos los type hidden en true, realiza el submit():
            if (1 == 1) {
                document.getElementById('formulario').submit();
            }
        });

        function upload(urlPath, name, result) {
            var isValid = undefined;
            var formData = new FormData();
            var file = document.getElementById(name).files[0];
            formData.append(name, file);
            $.ajax({
                type: 'post',
                url: urlPath,
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    $("#" + result).val(response.isValid);
                    $("#message" + result).text(response.message);
                    checkSingleStatus(name, response.isValid);                    
                    checkAllStatus();
                }
            });
        }

        function checkAllStatus() {
            var isValid = $('#fileStatus').val();

            if (isValid == "true") {
                $('#boton').prop("disabled", false);
            } else {
                $('#boton').prop("disabled", true);
            }

        }

        function checkSingleStatus(item, result) {
            if (item == "file") {
                if (result == true) {
                    $('#success').css("display", "inline");
                    $('#error').css("display", "none");
                }
                else {
                    $('#success').css("display", "none");
                    $('#error').css("display", "inline");
                }
            }
        }
    });
    </script>
}