GastoTransparenteMunicipal/GastoTransparenteMunicipal/Models/ServiceStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GastoTransparenteMunicipal.Models
{
    public class ServiceStatus
    {
        public bool DataBase { get; set; }
        public bool Email { get; set; }
        public bool BlobService { get; set; }
    }
}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Controllers/GastosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core;
using GastoTransparenteMunicipal.Models;

namespace GastoTransparenteMunicipal.Controllers
{
    public class GastosController : BaseController
    {
        // GET: Gastos
        public ActionResult Index()
        {
            var municipalidad = GetCurrentIdMunicipality();
            if (municipalidad == null)
                return RedirectToAction("List", "Home");
            if(string.IsNullOrEmpty(municipalidad.Periodo))
                return RedirectToAction("List","Home");
            ViewBag.logo = municipalidad.DireccionWeb + ".png";
            ViewBag.activos = new List<bool>{
                municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
            };
            ViewBag.Destacado = "hidden";

            List<Gasto_Ano_Visible> tiempos = db.Gasto_Ano_Visible.Where(r => r.IdMunicipalidad == municipalidad.IdMunicipalidad).OrderByDescending(r => r.Nombre).ToList();
            ViewBag.Anos = new SelectList(tiempos, "IdAno", "Nombre");
            ViewBag.Gasto = "active";
            return View();
        }

        //Consulta de que datos traer desde bdd.
        public ActionResult JsonGastoNivelX(string tipo, int? idNivel ,int? profundidad,int year)
        {
            #region FINAL
            D3Object_TreeMap d3 = new D3Object_TreeMap();
            
            string FUNCIONALECONOMICO = tipo;
            string NIVEL = idNivel.ToString();
            int PADRE = profundidad.Value;
            var idMunicipality = GetCurrentIdMunicipality();
            switch (NIVEL)
            {
                case "1":
                    List<Gasto_Nivel1> lista1 = db.Gasto_Ano.Find(year).Gasto_Nivel1.Where(r => r.Tipo == FUNCIONALECONOMICO && r.MontoGastado>0).OrderByDescending(r => r.MontoGastado).ToList();
                    
                    d3.Load(lista1, "0");        
                    break;
                case "2":
                    List<Gasto_Nivel2> lista2 = db.Gasto_Nivel2.Where(r => r.IdNivel1 == PADRE && r.Tipo == FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                    if (lista2.Count < 1)
                    {
                        lista2 = db.Gasto_Nivel2.Where(r => r.IdNivel1 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                        if (lista2.Count < 1)
                        {
                            d3.Load(lista2, "2");// 2= NO hay mas detalle
                        }
                        else
                        {
                            d3.Load(lista2, "1");// 1= Hay pero en otra categoria
                        }

                    }
                    else
                    {
                        if (!db.Gasto_Nivel2.Any(r => r.IdNivel1 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0))
                        {
                            d3.Load(lista2, "3"); // 1= Solo hay en la que eligio
                        }
                        else
                        {
                            d3.Load(lista2, "0");// 0= Hay normal
                        }
                    }
                    break;
                case "3":
                    List<Gasto_Nivel3> lista3 = db.Gasto_Nivel3.Where(r => r.IdNivel2 == PADRE && r.Tipo == FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                    if (lista3.Count < 1)
                    {
                        lista3 = db.Gasto_Nivel3.Where(r => r.IdNivel2 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                        if (lista3.Count < 1)
                        {
                            d3.Load(lista3, "2");// 2= NO hay mas detalle
                        }
                        else
                        {
                            d3.Load(lista3, "1");
                        }
                    }
                    else
                    {
                        if (!db.Gasto_Nivel3.Any(r => r.IdNivel2 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0))
                        {
                            d3.Load(lista3, "3");
                        }
                        else
                        {
                            d3.Load(lista3, "0");
                        }
                    }
                    break;
                case "4":
                    List<Gasto_Nivel4> lista4 = db.Gasto_Nivel4.Where(r => r.IdNivel3 == PADRE && r.Tipo == FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                    if (lista4.Count < 1)
                    {
                        lista4 = db.Gasto_Nivel4.Where(r => r.IdNivel3 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0).OrderByDescending(r => r.MontoGastado).ToList();
                        if (lista4.Count < 1)
                        {
                            d3.Load(lista4, "2");// 2= NO hay mas detalle
                        }
                        else
                        {
                            d3.Load(lista4, "1");
                        }
                    }
                    else
                    {
                        if (!db.Gasto_Nivel4.Any(r => r.IdNivel3 == PADRE && r.Tipo != FUNCIONALECONOMICO && r.MontoGastado > 0))
                        {
                            d3.Load(lista4, "3");
                        }
                        else
                        {
                            d3.Load(lista4, "0");
                        }
                    }
                    break;
            }
            string json = d3.getJson();

            return this.Content(json, "application/json");
            #endregion
        }

        //Creacion de JSON para mostrar en Treemap
        public class D3Object_TreeMap
        {
            public D3Object_TreeMap()
            {
                elementos1 = new List<string>();
            }
            private List<string> elementos1;
            private string json;
            private string formatter;
            private long total = 0;

            private string getCabecera()
            {
                string cabecera = @"{
                                     ""name"": ""flare"",
                                     ""children"": [";
                return cabecera;
            }
            private string getPie()
            {
                string pie = @"  ]
                                }";
                return pie;
            }
            private string createNivel1()
            {
                string childrens = "";
                for (int i = 0; i < elementos1.Count; i++)
                {
                    string aux = elementos1[i];

                    if (i + 1 == elementos1.Count)
                        aux = aux.Substring(0, aux.Length - 1);

                    childrens += aux;
                }
                return childrens;
            }

            public void setFormato(string formatter)
            {
                this.formatter = formatter;
            }
            public void addElementoNV1(string name, string size, string nivel, string tipo, string color, string id, string idRegion)
            {
                string auxElem = @"{
                             ""name"":" + @"""" + name + @"""" +
                                 @",""size"":" + @"""" + size + @"""" +
                                 @",""tipo"":" + @"""" + tipo + @"""" +
                                 @",""valueTooltip"":" + @"""" + size + @"""" +
                                 @",""nivel"":" + @"""" + nivel + @"""" +
                                 @",""id"":" + @"""" + id + @"""" +
                                 @",""idRegion"":" + @"""" + idRegion + @"""" +
                                 @",""color"":" + @"""" + color + @"""" + "},";

                elementos1.Add(auxElem);
            }
            public string getJson()
            {
                json = getCabecera() + createNivel1() + getPie();
                json = json.Remove(json.Length - 1, 1) + ", \"Format\":\"" + this.formatter + " \"}";
                json = json.Remove(json.Length - 1, 1) + ", \"TotalSuma\":\"" + total + " \"}";
                return json;
            }

            public void Load(List<Gasto_Nivel1> d3Object, string formatter)
            {
                this.formatter = formatter;

                foreach (var nv1 in d3Object)
                {
                    total = total + nv1.MontoGastado.Value;
                    addElementoNV1222(
                        nv1.Nombre,
                        nv1.MontoGastado.ToString(),
                        nv1.MontoPresupuestado.ToString(),
                        "1",
                        nv1.Tipo,
                        "#ea9393",
                        nv1.IdNivel1.ToString(),
                        nv1.PorcentajeGastado.ToString(),
                        nv1.PorcentajePresupuestado.ToString(),
                        nv1.Descripcion);
                }
            }
            public void Load(List<Gasto_Nivel2> d3Object, string formatter)
            {
                this.formatter = formatter;
                foreach (var nv1 in d3Object)
                {
                    total = total + nv1.MontoGastado.Value;
                    addElementoNV1222(
                        nv1.Nombre,
                        nv1.MontoGastado.ToString(),
                        nv1.MontoPresupuestado.ToString(),
                        "1",
                        nv1.Tipo,
                        "#ea9393",
                        nv1.IdNivel2.ToString(),

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Controllers/HomeController.cs
using GastoTransparenteMunicipal.Helpers;
using GastoTransparenteMunicipal.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GastoTransparenteMunicipal.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult ServiceStatus()
        {
            ServiceStatus serviceStatus = new ServiceStatus();
            ViewBag.Destacado = "hidden";
            ViewBag.activos = new List<bool>
            {
                false,false,false,false
            };
            ViewBag.logo = "municipio.png";
            return View(serviceStatus);
        }


        [HttpPost]
        public ActionResult ServiceStatus(string validator)
        {
            //validator = "v0#luptatem!ObservatorioConsejo!#";
            ViewBag.Destacado = "hidden";
            ViewBag.activos = new List<bool>
            {
                false,false,false,false
            };
            var municipios = db.Municipalidad.Where(r => r.Activa == true).ToList();
            ViewBag.logo = "municipio.png";

            ServiceStatus serviceStatus = new ServiceStatus();
            if (validator == "v0#luptatem!ObservatorioConsejo!#")
            {
                BlobService blobService = new BlobService(GetAccountName, GetAccountKey);
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    try
                    {
                        connection.Open();
                        serviceStatus.DataBase = true;
                    }
                    catch (SqlException)
                    {
                        serviceStatus.DataBase = false;
                    }
                }

                serviceStatus.Email = EmailService.CheckConnection();
                serviceStatus.BlobService = blobService.CheckConnection();

            }
            return View(serviceStatus);
        }

        //GET: Pagina de Inicio
        public ActionResult Index()
        {
            var municipalidad = GetCurrentIdMunicipality();
            if (municipalidad == null)
                return RedirectToAction("List");
            if (string.IsNullOrEmpty(municipalidad.Periodo))
                return RedirectToAction("List");
            if (municipalidad != null)
            {
                ViewBag.activos = new List<bool>
                {
                    municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
                };
                ViewBag.logo = municipalidad.DireccionWeb + ".png";
                ViewBag.Inicio = "active";
                ViewBag.Destacado = "hidden";
                ViewBag.texto1 = municipalidad.Periodo;
                ViewBag.texto2 = municipalidad.TotalGastado;
                ViewBag.texto3 = municipalidad.TotalPresupuestado;
                return View();
            }
            else
            {
                return RedirectToAction("NoExiste");
            }
            
        }

        //
        public ActionResult About()
        {
            var municipalidad = GetCurrentIdMunicipality();
            ViewBag.activos = new List<bool>
            {
                municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
            };
            ViewBag.logo = municipalidad.DireccionWeb + ".png";
            ViewBag.Destacado = "hidden";
            ViewBag.nombre = municipalidad.Nombre;
            var municipios = db.Municipalidad.Where(r => r.Activa == true).ToList();
            return View(municipios);
        }

        //GET: Cuando existe un error.
        public ActionResult Error()
        {
            return View();
        }

        //GET: Cuando no encuentra la url
        public ActionResult Error404()
        {
            return View();
        }

        //GET: Vista comodin de informacion.
        public ActionResult List()
        {
            ViewBag.Destacado = "hidden";
            var municipalidad = GetCurrentIdMunicipality();
            if (this.User.Identity.IsAuthenticated)
            {
                ViewBag.administracion = true;
                if (!this.User.IsInRole("admin"))
                {
                    ViewBag.admimuni = true;
                    ViewBag.logo = (municipalidad != null) ? municipalidad.DireccionWeb + ".png" : "municipio.png";
                }
            }
            else
            {
                if (municipalidad != null)
                {
                    ViewBag.activos = new List<bool>
                    {
                        municipalidad.Act_Proveedor,municipalidad.Act_Subsidio,municipalidad.Act_Corporacion,municipalidad.Act_Personal
                    };
                    var municipios = db.Municipalidad.Where(r => r.IdMunicipalidad == municipalidad.IdMunicipalidad).ToList();
                    ViewBag.logo = municipalidad.DireccionWeb + ".png";
                    return View(municipios);
                }
                else
                {
                    ViewBag.activos = new List<bool>
                    {
                        false,false,false,false
                    };
                    var municipios = db.Municipalidad.Where(r => r.Activa == true).ToList();
                    ViewBag.logo = "municipio.png";
                    return View(municipios);
                }

            }

            var listaMunicipios = db.Municipalidad.Where(r => r.Activa == true).ToList();
            return View(listaMunicipios);








        }
        
        //Descarga de Dataset de las visualizaciones.
        public JsonResult Descarga(int year, string origenData)
        {
            string aux = "";
            switch (origenData)
            {
                case "ingresos":
                    aux = db.Ingreso_Ano.Find(year).DataFilePath;
                    break;
                case "gastos":
                    aux = db.Gasto_Ano.Find(year).DataFilePath;
                    break;
                case "corporaciones":
                    aux = db.Corporacion_Ano.Find(year).DataFilePath;
                    break;
                case "subsidios":
                    aux = db.Subsidio_Ano.Find(year).DataFilePath;
                    break;
                case "proveedores":
                    aux = db.Proveedor_Ano.Find(year).DataFilePath;
                    break;
                case "sueldos":
                    aux = db.Personal_Ano.Find(year).DataFilePath;
                    break;
            }
            return Json(aux, JsonRequestBehavior.AllowGet);
            //return this.Content(aux, "application/json");
        }
    }
}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/Home/Error404.cshtml
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <title>¡Error!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p><br /><br /></p>
            </div>
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1 class="display-4">Lo sentimos!</h1>
                    <p class="lead">La URL solicitada / no fue encontrada o no se encontró en este momento.</p>
                    <hr class="my-4">
                    <p>Si consideras que es un error de la plataforma, favor de enviar un correo a contacto@cuentasclaras.de para poder solucionarlo lo antes posible.</p>
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="javascript:history.back(2)" role="button">Volver</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="row">
        <div class="col-12 homefont">
        </div>
        <div class="relative">
            <p class="text-center">
                <img class="img-fluid" src="~/Content/image/municipiosblanco/@ViewBag.logo" />
            </p>
            <h3 class="text-center blanco small-display">
                <small>Bienvenido al Gasto Transparente Municipal</small>
            </h3>
            <h3 class="text-center blanco container">
                @ViewBag.texto1, la Municipalidad <span class="amarillo">gastó @ViewBag.texto2 Millones de pesos</span> <small>de un presupuesto anual de</small> @ViewBag.texto3 Millones de pesos.<br>
            </h3>
            <div class="small-display">
                <p class="text-center blanco">
                    <small>¿De donde se obtuvo y como se usó ese dinero?<br>Te ayudaremos a encontrar las respuestas.</small>
                    <br>
                    <div class="arrows"></div>
                </p>
            </div>
        </div>
        

</div>
<div class="row">
    <div class="col grisB padding-Div" id="IngresoGastos">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center">
                    <h2>¿De dónde provienen los recursos?</h2>
                    <p><br>Conoce los ingresos percibidos por patentes municipales, permisos de circulación, aportes del gobierno, entre otros, en cada una de las áreas: Salud, Educación, Servicios Municipales y Cementerios.<br><br></p>
                    <a href="@Url.Action("Index","Ingresos")" class="btn">Ingresos</a>
                </div>
                <div class="col-md-6 text-center">
                    <h2>¿Cómo se usa ese dinero?</h2>
                    <p><br>Conoce los gastos realizados en las áreas: Salud, Educación, Servicios Municipales y Cementerios, o según tipo de cuentas, entre los cuales se encuentran: Personal, compra de bienes y servicios o aportes externos.<br><br></p>
                    <a href="@Url.Action("Index","Gastos")" class="btn">Gastos</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col padding-Div">
        <div class="container">
            <div class="row">
                <div class="col-md-6 padding-cero">
                    <h2>Datos destacados</h2>
                    <p>
                        Analiza cómo se gastan los recursos del municipio en conceptos de interés, como el personal, las compras a proveedores, las subvenciones a organizaciones comunales, y los aportes municipales a las corporaciones.
                        <br><br><br>
                    </p>
                </div>
            </div>
            <div class="row">
                @if (ViewBag.activos[3])
                {
                    <div class="col">
                        <div class="card">
                            <div class="card-body text-center">
                                <a href="@Url.Action("Sueldos","DatosDestacados")">
                                    <span class="md-96 icon-Recurso2"></span>
                                    <p><br>¿Cual es el sueldo promedio por tipo de funcionario?</p>
                                </a>
                            </div>
                        </div>
                    </div>
                }
                @if (ViewBag.activos[0])
                {
                    <div class="col">
                        <div class="card">
                            <div class="card-body text-center">
                                <a href="@Url.Action("Proveedores","DatosDestacados")">
                                    <span class="md-96 icon-Recurso3"></span>
                                    <p><br>¿A quiénes le <br> compramos?</p>
                                </a>
                            </div>
                        </div>
                    </div>
                }
                @if (ViewBag.activos[1])
                {
                    <div class="col">
                        <div class="card">
                            <div class="card-body text-center">
                                <a href="@Url.Action("Subsidios","DatosDestacados")">
                                    <span class="md-96 icon-Recurso7"></span>
                                    <p><br>¿A quiénes<br>  subsidiamos?</p>
                                </a>
                            </div>
                        </div>
                    </div>
                }
                @if (ViewBag.activos[2])
                {
                    <div class="col">
                        <div class="card">
                            <div class="card-body text-center">
                                <a href="@Url.Action("Corporaciones","DatosDestacados")">
                                    <span class="md-96 icon-Recurso1"></span>
                                    <p><br>¿Cómo se financian nuestras Corporaciones?</p>
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(".destacado").hover(
            function () {
                $(".destacado").css("background-color", "#f5f9ff");
                $("#destacado-barra").removeClass("hidden");
                $(".borde-menu").css("border-bottom", "1px solid");

            }, function () {
                $(".destacado").css("background-color", "#ffffff");
                $("#destacado-barra").addClass("hidden");
                $(".borde-menu").css("border-bottom", "0px");
            }
        );
    </script>
}

GastoTransparenteMunicipal/GastoTransparenteMunicipal/Views/Home/ServiceStatus.cshtml
@model GastoTransparenteMunicipal.Models.ServiceStatus

@{
    ViewBag.Title = "Estado de servicios";
}


<div class="row">
    <div class="col-12 homefont">
    </div>
    <div class="relative margin-top">
        <p class="text-center">
            <img class="img-fluid" src="~/Content/image/municipiosblanco/municipio.png" />
        </p>
        <h3 class="text-center blanco ">
            Bienvenido al <br /> Portal de Cuentas Claras Municipal
        </h3>
        <p class="text-center blanco">“Por una rendición de cuenta entendible para el vecino”</p>
    </div>
</div>
<div class="row">
    <div class="container">
        <div class="col-12">
            <h1>Estado de los Dependencias.<br /><br /></h1>
        </div>
        @if (Model.BlobService == false && Model.Email == false && Model.DataBase == false)
        {
            <form action="@Url.Action("ServiceStatus","Home")" method="post">
                <input type="password" class="form-control" id="validator" name="validator" placeholder="Contraseña" /><br />
                <button class="btn">Comprobar</button>
            </form>
        }
        else
        {
            <div class="col-12">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 salto">
                            <table class="table-responsive">
                                <thead>
                                    <tr>
                                        <th>
                                            Servicio
                                        </th>
                                        <th>
                                            Estado
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            Base de datos
                                        </td>

                                        @{if (Model.DataBase == true)
                                            {
                                                <td>
                                                    Correcto
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    No disponible
                                                </td>
                                            }
                                        }
                                    </tr>
                                    <tr>
                                        <td>
                                            Email
                                        </td>
                                        @{if (Model.Email == true)
                                            {
                                                <td>
                                                    Correcto
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    No disponible
                                                </td>
                                            }
                                        }
                                    </tr>
                                    <tr>
                                        <td>
                                            Blob service
                                        </td>
                                        @{if (Model.BlobService == true)
                                            {
                                                <td>
                                                    Correcto
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    No disponible
                                                </td>
                                            }
                                        }
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row padding-Div">
                    </div>

                    <div class="row padding-Div">
                    </div>
                </div>
            </div>
        }

    </div>
</div>

<div class="row padding-Div">
</div>
    